[client]
showSidebarNavigation = false

[theme]
base="dark"
primaryColor="#32fcff"
backgroundColor="#23232b"
secondaryBackgroundColor="#383844"

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"
